### ISSUE TITLE
Circuit browser - enforce root and destination positions

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1078]
Currently sometimes the root and destination get in column with other elements and is difficult to understand which one is the root node and the destination in the graph displayed.
It would be better to have the root positioned on the left of the graph alone and the destination on the right alone.

**Comment by ddelpiano** [comment]
@jrmartin I put a cap of 5 hours on this card but please before to reach that, after you spend a couple of hours on this card please sync with @Robbie1977 and @gidili to understand the level of complexity in implementing this solution since what currently implemented might be enough already.

**Comment by jrmartin** [comment]
@Robbie1977 @gidili 
The reason why the position of the root and destinations is not always enforced is because of the results coming back from the query. Some destinations nodes are coming back with paths linking it to 'children' nodes.

For example, doing a query for nodes : 'VFB_jrchjrch','VFB_jrchjsfu', 'VFB_jrchjs1t'  and hops : 3, we see that destination node (VFB_jrchjsfu) has a bidirectional path to a 'children' node (VFB_jrchk4rt). Node VFB_jrchk4rt is only linked to destination node VFB_jrchjsfu, so the graph automatically draws it as a child of VFB_jrchjsfu. 
![Screenshot from 2021-04-08 12-01-44.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/2e682a0a-57e1-4617-8849-e10245a259cc)

Using example above but with hops : 2, the destination nodes don't have children paths and we get the nodes in their preferred positions. 
![Screenshot from 2021-04-08 12-38-57.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/2611e1f1-5331-4144-94eb-6f74be9ee6f8)

One way to fix this is for the query to return destinations nodes without paths linking it to 'children nodes',  if we don't need them. 

Otherwise, we can reposition those 'children' nodes like VFB_jrchk4rt, and move them to the left of the destination nodes. This would take time to do, since we would need to play with the canvas geometries and reposition everything to the right of the destination nodes).

**Comment by Robbie1977** [comment]
@jrmartin we are aiming to remove these loopback children in the query so you don't need to worry about them from the display side.

**Comment by ddelpiano** [comment]
@Robbie1977 I am leaving this one until we check together once the loopback children are removed and see if we are happy with the result, differently we will need to go forward with what Jesus suggested above.
