### ISSUE TITLE
Improve Layout and Links on Circuit Browser

### ISSUE THREAD

**Issue by jrmartin** [VirtualFlyBrain/geppetto-vfb#1114]
- Currently the problem is the source and target are hard to workout, also the specific paths are not clear.
- Sometimes the links arrows are hidden behind nodes, which makes it impossible to figure out the target and source of the link without the arrow. 

Image of issue : 
![image](https://user-images.githubusercontent.com/4562825/115073650-7e464f80-9ead-11eb-8221-0eff5739d78c.png)

@Robbie1977 made changes to the query results so they return a dictionary of id's and position numbers. 

Results are returning : 

```
source	target	maxHops	relationshipY
73271	74501	5	["5411947:0", "6607174:1", "6670395:1", "6944221:1", "5411947:1", "7159128:1", "7609748:2", "7585761:2", "5411947:2", "5174191:2", "7463645:2", "6944221:2", "7180415:3", "4974421:3", "5411947:3", "7823673:3", "4946512:3", "6944221:3", "5411947:4", "6944221:4", "4893596:4", "6480518:4", "4436902:4"]
```
This gives the source node (far left) target node (far right)
Max hops is the max hops for the longest route so give an X gap to space the source and target by
relationshipY is the Y position to put the arrows could do ODD below and EVEN above increasing the step each time or simply step down each time below.

`RelationshipId:index
`

0 is always the shortest path getting longer this is also by weight strength so not just hops.

**Comment by Robbie1977** [comment]
See 'A' in this figure for the idea of ordering by path length:

![image.png](https://images.zenhubusercontent.com/5964e5f861b4ca3b0a7400b0/b8ecf56f-8d30-4aea-9fc5-8db20ed49101)

**Comment by ddelpiano** [comment]
Quick recap on the implementation required for this card.

** Layout improvements: **

- root and destination nodes must be placed on the most extreme left and right sides of the graph
- if more than 2 nodes are set in the configuration panel we will follow the same approach so that the first is the root and the last the destination, all the others will be fitted somewhere in a level in the middle
- all the other nodes should be placed by level as per image pointed out by Robb
- to compute to which level a node belongs to we should:

1. from the results given 

```
source	target	maxHops	relationshipY
73271	74501	5	["5411947:0", "6607174:1", "6670395:1", "6944221:1", "5411947:1", "7159128:1", "7609748:2", "7585761:2", "5411947:2", "5174191:2", "7463645:2", "6944221:2", "7180415:3", "4974421:3", "5411947:3", "7823673:3", "4946512:3", "6944221:3", "5411947:4", "6944221:4", "4893596:4", "6480518:4", "4436902:4"]
```

We should build a dictionary with array per level, something similar to

```
graph = { '0': ["source", "target"],
               '1': ["node1", "node2", etc..] }
```

We should loop the relationshipY array following the Y order (:0, :1, etc), for each relationship we should check which nodes belongs to this and check if the startNode and endNode are already listed the in dictionary, if yes ignore that node, if not place it in the level pointed out by the Y integer.
At the end the graph dictionary will be listing all the nodes ordered per level, property that we can use in each node instance of the graph that will be created by force-graph.

The end results will be something similar to this:

![screenshot (7).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/24b21f94-1890-4ec0-aaf6-ad42d4f14c63)

** Links improvements **
- connections should originate from the angle of each node rather than from the core/center
- connections might be straight lines if it helps (would it be possible to expose this to the json configuration of the component so that Robbie can easily tweak if he wants to have straight or curve connections? Thx).

After the 2 improvements above let's do a round of testing, if still problematic to see the connections we should spend a bit of time in the below:
- explore the possibility that when the user hover a connection this gets an higher z-index than the rest and go over nodes and anything else so that the user can easily see the connection.

**Comment by ddelpiano** [comment]
Layout improvements:

- go back to single line
- get rid of the curve and put straight lines for the connections
- the reverse value should go in brackets as before, so "weight [reverse weight]" should be displayed in the connection
- calculate hops and put nodes per column along with the level


Current issues with the layout:

Note, the issue below might not require any action since we will have to position nodes on the x other that the y, so this below should be already addressed.

(please, note the weight number, 'VFB_jrchjrch' and 'VFB_jrchjsfu' are the ids used) 
![screenshot (2).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/737dd70f-c69b-4c24-84c7-6b43810fc69a)

**Comment by jrmartin** [comment]
Hello @Robbie1977, the current query we are using in development branch is not returning an array with forward relationships only as we had before, we were using the array with forward relationships to render links going only one way and avoid loops. 

Current query we are using is the one in development : https://github.com/VirtualFlyBrain/geppetto-vfb/blob/development/components/configuration/VFBCircuitBrowser/circuitBrowserConfiguration.js#L4

To avoid the loops, we had the line in the middle of this block before, but it's missing in the newest query. Where do we add it in the new query?  
` 
  + " ALL(rel in relationships(p) WHERE exists(rel.weight) AND rel.weight[0] > " + weight.toString() + ")"
  + " AND none(rel in relationships(p) WHERE endNode(rel) = x OR startNode(rel) = y)"
  + " WITH root, relationships(p) as fu, p AS pp"
`

**Comment by dosumis** [comment]
@Robbie1977 - can we make sure the return clause on these queries is standardised so return is predictable. Could write a quick JSON schema & use to test

**Comment by jrmartin** [comment]
@Robbie1977 Regarding the previous request to avoid loops in the query results, I figured out we can calculate this now ourselves using the the relationshipY:hops. Since it's possible now to know which links are in reverse order, we don't need the array with the forward links in the results anymore.

**Comment by jrmartin** [comment]
@ddelpiano @Robbie1977 This PR includes the adjusted destination spacing talked during the sprint call
