### ISSUE TITLE
circuit browser - link from term info does not work

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1144]
same issue flagged few weeks ago.
Searched for VFB_jrchjrch, went to the term info, used the link to add the instance in the circuit browser and I do not see the input text on top completed with that.

could we add a test for this as well please? Thx

**Comment by jrmartin** [comment]
@Robbie1977 @ddelpiano What happens if the two textfields are already populated with neurons, and the user opens up the circuit browser from the term info with a neuron different than the one already on the textfields? Do we replace one of the neurons on the textfield with the one coming from the term info? Since the queries are only working for two neurons, adding an extra textfield for the term info neuron wouldn't work.

**Comment by ddelpiano** [comment]
@jrmartin ideally this should work like a circular queue and the size of the queue depends by the max number of neurons we can configure from the hson file.
So assuming we are working with only 2 neurons like now, we fill index 0, next we fill index 1, if the user use again the term info link then we restart from the beginning of the circular queue and so on.
@Robbie1977 does this make sense or do you prefer a different implementation? Thx
