### ISSUE TITLE
direction of paths not following given forward path.

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#1161]
for example:
For VFB_jrchjuok -> VFB_jrchju5h
6 paths with min weight of 5
![image](https://user-images.githubusercontent.com/4630768/126141079-03ba48d7-24be-4fce-9788-76c1aa9f67dd.png)
Note the path shows a forward path with a weight of 2 (not >=5).
Having looked at the forward path (fp/pp) returned and the forward route edge/relationship ID list (fr): 
[6352006, 4849985, 7215934, 4514396, 6525430, 6492590, 4869357, 6658599, 5069831, 4702069, 5256304, 6085202, 6690678, 6044724, 6640077]
The 8 edge (id: 64925090) is listed as a forward route and not the 2 edge (id: 4443032).
The forward path for this query is returned as:
![image](https://user-images.githubusercontent.com/4630768/126142421-9e9b952f-e930-4a61-851d-860158c40537.png)

**Comment by Robbie1977** [comment]
@jrmartin note: there was an issue with the naming of variables that is now fixed in dev so best to take a new fork.

**Comment by jrmartin** [comment]
@Robbie1977 This bug is fixed now on feature/1161
![image](https://user-images.githubusercontent.com/4562825/126541378-0bf856b3-0657-4db0-afe5-c5c1a389f9a2.png)

I spent an extra couple of hours fixing another bug. 
For the case of neurons VFB_00100696 and VFB_00100690 with weight 5 and paths 6, one of the graph nodes was hidden, now it's visible. 
![image](https://user-images.githubusercontent.com/4562825/126542138-e7c44271-4d10-40c4-9331-6872a0092aba.png)
