### ISSUE TITLE
Create tree browser

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/geppetto-vfb#172]
Tree browser widget displays domains on templates http://visjs.org/network_examples.html

**Comment by ddelpiano** [comment]
Tree browser (not connected nodes) for template: single root or small number of roots - many branches and leaf nodes. This one should be folded out to some limited number of nodes. Would also be good if automatically folds out to focus term (this is what VFB1 does). (from @dosumis from the card https://app.zenhub.com/workspaces/vfb15-59c292c4286ea849ed3c9326/issues/virtualflybrain/geppetto-vfb/337 )

**Comment by dosumis** [comment]
Old draft cypher queries for generating graphs from templates here:

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/f3de5ac921d410232b03aa616198f8ac89aa8a47/doc/draft_queries.md#generating-trees-for-a-given-template

@Robbie1977 may have more recent versions. 

Note - query efficiency might be an issue here.  If so, we may wish to cache JSON for templates (?)

**Comment by Robbie1977** [comment]
Latest one is https://github.com/VirtualFlyBrain/VFB/blob/Main-Server/javascript/vfb/anatomyTree.js#L59

**Comment by ddelpiano** [comment]
Requirements from @dosumis - copy paste from the other card.

### Query

```.cql
MATCH (root:Class)<-[:INSTANCEOF]-(t:Individual { short_form : 'VFB_00017894'})
<-[:depicts]-(tc:Individual)<-[ie:in_register_with]-(image:Individual)
-[:depicts]->(anat__ind:Individual)-[:INSTANCEOF]->(ac:Class) 
WHERE has(ie.index) 
WITH root, 
COLLECT (ac.short_form) as tree_nodes, 
COLLECT (DISTINCT{ image: image.short_form, anat_ind: anat_ind.short_form, 
type: ac.short_form}) AS domain_map 
MATCH p=allShortestPaths((root)<-[:SUBCLASSOF|part_of*..]-(anat:Class)) 
WHERE anat.short_form IN tree_nodes RETURN p, domain_map
```

### Description of query:

For a given template (in this case  'VFB_00017894'), find the anatomical type of the template (root class), all individuals*1 representing painted domains*2 on this template and the classes specify their anatomical type.  For all the classes found by this query, find all shortest paths between these classes and the root. 

\*1  anatomical individuals and the images that depict them
\*2  painted domains are selected on the assumption that all have an index on the in_register_with edge linking to template, rather than by image individual type.

### Description of results:

*p* = D3 JSON graph - nodes = classes (types) in domain_map

*domain_map*  = list of dicts, each mapping 3 IDs associated with each node:

```.js
{
                "image": "VFBc_00030615",
                "anat_ind": "VFB_00030615",
                "type": "FBbt_00045039"
              },
              {
                "image": "VFBc_00030612",
                "anat_ind": "VFB_00030612",
                "type": "FBbt_00003885"
              }....
```

### Post_processing required to drive tree widget

Details TBA

### Tree widget spec 

- Tree structure comes from D3 graph (postprocessed to tree widget input)
- Name comes from domain_map.type
- Selection of tree item -> anat_ind becomes focus term
- If focus term = Type or anat_ind -> open tree to corresponding node(s)
- TBA: each node in tree should have a checkbox.  Selection of checkbox => addition of corresponding image to stack browser & canvas.  Deselection of checkbox => removal (Need to be careful about how this works with control panel)

**Future extensions:**

- Search in tree (autocomplete) -> select ->  open tree to selected nodes
- Add color choice icons & centre icon to each node

**Comment by ddelpiano** [comment]
- Take cypher query out from the component and place it in the configuration.
- change onClick behaviour, remove the i-info and if you click on label it will display on the term info, the arrows instead will drive the navigation.
- expand on instance selection not working (bug!).
- Label will show tooltip with the thumbnail, remove the info icon.
- vertical size of the boxes to be reduced.
- Search not trivial, on hold for now.
- Color picker to be included.

**Comment by ddelpiano** [comment]
Swap with the Slider component from the same library.
Remove border.
Eye icon to hide/show on the parent and not the individual.
instanceOnFocus when passed to the TreeBrowser to check the tree, if the id is present pass to searchQuery the class id so the tree will explode also on individual ids.
