### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#220]
```gpt-shapeshow``` has gone blank though ```gpt-shapehide``` is fine!?
Affecting all sites so not sure when it started:
https://v2.virtualflybrain.org/?i=VFB_00017894

**Comment by Robbie1977** [comment]
Caused by: https://github.com/openworm/org.geppetto.frontend/commit/67aaa177770795e6a7958558f34b7ba019d7378f#diff-48c70e1c04150801dbb91dd3653ac18b

**Comment by ddelpiano** [comment]
to be discussed with @tarelli when back.

**Comment by tarelli** [comment]
@ddelpiano @Robbie1977 fixed, the icon wasn't getting generated even though the file was there, after some digging I realised that that specific icon had the raster version instead of the vector one. A newer version of the font generator must have stopped dealing with those. New font generated and pushed to development.

**Comment by Robbie1977** [comment]
deployed and tested here: https://v2-dev.virtualflybrain.org/?i=VFB_00017894
