### ISSUE TITLE
Issues with 3D Canvas responsiveness  

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#247]
Rotation is extemely slow to initiate on chrome in:
https://v2.virtualflybrain.org/?i=VFB_00100000,VFB_00064847

**Comment by Robbie1977** [comment]
Marta is getting the issue on Chrome Version 69.0.3497.81 (Official Build) (64-bit) and also find Safari works much better.
I'm on Version 68.0.3440.106 (Official Build) (64-bit) (noticed this before neurofly) and Safari Version 11.1.2 (13605.3.8)

**Comment by Robbie1977** [comment]
stepping through the code it seems the ```that.getIntersectedObjects()``` (https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js#L142) is adding the delay so maybe just resolving https://github.com/VirtualFlyBrain/geppetto-vfb/issues/213 would remove this issue. Although the delay maybe a sign of an issue in the ray casting code itself.

**Comment by jrmartin** [comment]
Implementing issue #213 helps with canvas responsiveness. However, there's still a bit of lagging if the user tries rotation at the same time the Point cloud for VFB_00064847 is been rendered. There's also a bit of a delay when selecting objects in this template, Three.Raycaster's method intersectObjects() ( https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/3dCanvas/ThreeDEngine.js#L548) can take a while (locally i tested the time to be ~1 to 2 seconds sometimes). Debugging the raycaster class inside the Three.js library i see that there's a for loop going through all vertices of the selected object and in the case of VFB_00064847's point cloud is a for loop with 367578 vertices which may be the cause of the delay.

**Comment by Robbie1977** [comment]
This doesn't look like it will be fixed by Three.js any time soon: https://github.com/mrdoob/three.js/issues/12857 
Anything we can do from our end to make the problem simpler?

**Comment by Robbie1977** [comment]
@jrmartin would the answer to this help: 
```

down vote
accepted
@WestLangley gave me the answer in GitHub.

He said:
"Your bounding box has no volume. Try this and report back:

 pointCloud.geometry.boundingBox = null;
"

I tried and it worked out of the box!. And the detection is working even better than before.

Something that @Beiller pointed out in the comments, and is important to include here I think.

I had a call to

this.geometry.computeBoundingBox();
...for my geometry, but the points are not volumes, so single point or aligned (in one of the three axis: x, y or z) points are not detected. Using instead:

this.geometry.computeBoundingSphere() 
solve the problem too.
```
https://stackoverflow.com/questions/34009220/three-js-raycaster-intersectobject-do-not-intersect-when-three-points-has-only-1

**Comment by jrmartin** [comment]
@Robbie1977 Unfortunately not. Setting the bounding box to null won't make the geometry be less dense and have fewer vertices. 

"Anything we can do from our end to make the problem simpler?"
We could display a loading spinner with message "selection in progress...", similar to what we have at startup with "loading scene..." , when the user selects an object with a geometry with hundreds of thousands of vertices or any complex mesh. Having the loading spinner come up will prevent the user from interacting with the canvas, doesn't make selection any faster but at least it's more user friendly by letting the user know something is going on instead of having the canvas freeze. 

To improve the selection time we can try this https://github.com/gkjohnson/threejs-fast-raycast, somebody implemented a faster raycast class, can't say if it really works though.
