### ISSUE TITLE
feature/react_refactoring: opening search/query not focusing cursor 

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#268]
on opening search or query (using button bar) typing doesn't work without selecting the text box.

**Comment by ddelpiano** [comment]
@Robbie1977 this is now fixed, as mentioned in the other card I am re-using the pre-existing method to open these components since the logic to focus was already implemented in spotlight, querybuilder required a minor addition in the frontend bundle to mirror the same behaviour (this was not available even before, you can try on v2).

**Comment by Robbie1977** [comment]
Yep is live and works
