### ISSUE TITLE
feature/react_refactoring: Latest selection oddities

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#275]
The top bar is possibly interfering with the selection of objects at top of the screen.

Burrowing is having issues I suspect when the template has multiple planes in the ray.

https://youtu.be/PMZmxpFQ-wA

**Comment by ddelpiano** [comment]
@Robbie1977 if you agree I would suggest to remove the transparency and mirror the behaviour we currently have with the iframe and the border.
I don't see another easy solution since that object is floating over the canvas to avoid the issue I described in the last sprint meeting, open to suggestions from @gidili and @tarelli as well if you guys would tackle this differently.

**Comment by jrmartin** [comment]
![screenshot from 2018-10-25 16-38-42](https://user-images.githubusercontent.com/4562825/47533835-e1c20a00-d87a-11e8-9c39-d3e5be86d377.png)

The Issue
The problem is that the "div" elements holding the top bar and the tool bar (red background on screenshot) are rendered on top of the canvas, and just like the case of popups or any other widgets, the user can't click on canvas area where there's another "div" element rendered. Playing with the z-index doesn't help, I've tried giving the top and tool bar low z-index and canvas a high one and issue persists.   

For solution
For the toolbar, we can resize the div to get rid of the extra empty space, that takes care of that. 
For the top bar, even if we reduce the height to get rid of the extra space, we will still have empty space in between the components of top bar (space between fly logo and "Beta Testing" label and space between that and buttons to the right). I'd suggest instead of having a single "div" element for the top bar with all the components inside, we split  it into three components: One with the fly logo and text next to it, another one with title "Beta Testing site" label and another component holding the buttons to the right. Each of those three components would be added to the canvas separately and there wouldn't be all that empty space over the canvas interfering with selection.

**Comment by jrmartin** [comment]
Found a much more easy and neat trick

"A silly hack I did was to set the height of the element to zero but overflow:visible; combining this with pointer-events:none; seems to cover all the bases.

.overlay {
    height:0px;
    overflow:visible;
    pointer-events:none;
    background:none !important;
}"
Tested it and works, just needs some touches to the css of the top bar here and there

**Comment by gidili** [comment]
@jrmartin that sounds good to me if it works ! 👍 We are gonna soon have the canvas in its own widget so this will become redundant then but for now it's ok if it does the trick, let's just make sure to test in both chrome and firefox 😄

**Comment by jrmartin** [comment]
Fix and pull request https://github.com/VirtualFlyBrain/geppetto-vfb/pull/277
