### ISSUE TITLE
Tree widget prototype

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#375]

**Comment by ddelpiano** [comment]
@Robbie1977 could you paste the text-json that I need to use to produce the tree please ?

**Comment by ddelpiano** [comment]
- From the json, for now for the prototype takes labes, that are collapsed, and when clicking on them expand, change focus, and display id and expand to focus term.

- If the focus term change then the tree automatically will select and expand on the same item.

- If I have duplicates takes the first occurrence in the tree.

**Comment by ddelpiano** [comment]
https://github.com/VirtualFlyBrain/VFB/blob/master/javascript/vfb/anatomyTree.js

**Comment by dosumis** [comment]
Not sure this is the right ticket for documentation of this widget. If not, please move

### Query

```.cql
MATCH (root:Class)<-[:INSTANCEOF]-(t:Individual { short_form : 'VFB_00017894'})
<-[:depicts]-(tc:Individual)<-[ie:in_register_with]-(image:Individual)
-[:depicts]->(anat__ind:Individual)-[:INSTANCEOF]->(ac:Class) 
WHERE has(ie.index) 
WITH root, 
COLLECT (ac.short_form) as tree_nodes, 
COLLECT (DISTINCT{ image: image.short_form, anat_ind: anat_ind.short_form, 
type: ac.short_form}) AS domain_map 
MATCH p=allShortestPaths((root)<-[:SUBCLASSOF|part_of*..]-(anat:Class)) 
WHERE anat.short_form IN tree_nodes RETURN p, domain_map
```

### Description of query:

For a given template (in this case  'VFB_00017894'), find the anatomical type of the template (root class), all individuals*1 representing painted domains*2 on this template and the classes specify their anatomical type.  For all the classes found by this query, find all shortest paths between these classes and the root. 

\*1  anatomical individuals and the images that depict them
\*2  painted domains are selected on the assumption that all have an index on the in_register_with edge linking to template, rather than by image individual type.

### Description of results:

*p* = D3 JSON graph - nodes = classes (types) in domain_map

*domain_map*  = list of dicts, each mapping 3 IDs associated with each node:

```.js
{
                "image": "VFBc_00030615",
                "anat_ind": "VFB_00030615",
                "type": "FBbt_00045039"
              },
              {
                "image": "VFBc_00030612",
                "anat_ind": "VFB_00030612",
                "type": "FBbt_00003885"
              }....
```

### Post_processing required to drive tree widget

Details TBA

### Tree widget spec 

- Tree structure comes from D3 graph (postprocessed to tree widget input)
- Name comes from domain_map.type
- Selection of tree item -> anat_ind becomes focus term
- If focus term = Type or anat_ind -> open tree to corresponding node(s)
- TBA: each node in tree should have a checkbox.  Selection of checkbox => addition of corresponding image to stack browser & canvas.  Deselection of checkbox => removal (Need to be careful about how this works with control panel)

**Future extensions:**

- Search in tree (autocomplete) -> select ->  open tree to selected nodes
- Add color choice icons & centre icon to each node
