### ISSUE TITLE
Performance profiling

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#491]

**Comment by ddelpiano** [comment]
@dosumis could we get some scenes with list of items loaded that are worrying you the most? 
Thx!

**Comment by dosumis** [comment]
Performance of loading from external link in general is poor.  

We use a simple linking pattern  for linking to a  single image or class from outside:

http://www.virtualflybrain.org/reports/VFB_00021875

redirect is fast, (QuickHelp needs to be off!) but  then first it loads the  template TermInfo and chugs for some time before the chosen  content  appears in TermInfo.  We just had a user complain that links from FlyBase didn't work.  Page took so long to load that they started a search rather than wait.
