### ISSUE TITLE
Circuit browser requirements

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#560]
This component will shows the connection between 2 (or more) neurons, the number of hops will be defined by the user through the UI.
The requirements below are kept in line with what discussed in this card

# Requirements:

## Mockups:
https://www.figma.com/proto/qVNgJOFk329MDkt87UNKhi/Virtual-Fly-Brain?node-id=273%3A466&scaling=min-zoom
**Note: this component won't need the sync icon (since it's not following the focus term but it will be generated by the IDs inputed by the user) and the hamburger icon since we will have a single cypher query.
They are in the mockups due to the fact that we using an image of the current implementation, but we do not need sync and hamburger icons.**

## Inputs:
- If the inputs are emtpy/no graph is displayed then the configuration modal should be open by default.
- short_form IDs of **2 or more** neurons.
  - The json configuration should include a max number of neurons the user could input. If this is defined in the configuration the user won't be able to spawn more input texts than the number defined in the configuration.
- number of hops defined through a slider in the UI, the **boundaries of the slider** (min and max) needs to be **defined through json configuration file**, where the **default value will be the average**.

## Graph:
- The graph displayed will use the **same style** of what we currently generate with **the graph component**.
- The **orientation** of the graph is still an **open topic**, the **first implementation** will display the graph using the **same algorithm** we currently use for the **graph component**, this might be refined further after UX testing. Ideally this should be an option in the json configuration so that the VFB team can tweak this between different options later on (horizontal instead of vertical, centered, or other options).
- **Each node** will be filled by **different colours**, the color will be **driven by a pre-set list/function** that Robb and David will provide us. The colour will be driven by the "labels" field present in each node structure.
- Edges can have weights. These should be displayed as both annotations on the edge and as line-thickness. ( @dosumis @Robbie1977 what data do we have to use to highlight the line thickness? Thx).

## Query/queries:
- The **query** should be **able to extend itself** in relation to the number of neurons we decide to input.
- We can start the implementation temporarily with the query below, @dosumis and @Robbie1977 will provide a new query and how to tweak the query itself as soon as we increase the number of neurons:

WITH ['FBbt_00002303',  'FBbt_00002442'] AS neurons 
MATCH p=(x:Class)-[:synapsed_to*..4]->(y:Class)
WHERE x.short_form in neurons and y.short_form in neurons 
RETURN p, len(neurons) and length, neurons

## Term Info:
- If the instance displayed in the term info is a neuron, the **term info will provide a link to add this instance to the circuit browser**. I will add more granularity mockups side on this point later, you can assume that if the instance displayed in the term info is a neuron type we will need to add a link in the term info similar to what we already did with the graph component already. Single link and this link will add this instance ID to the configuration.

**Comment by dosumis** [comment]
Spec:

Inputs:
    short_form IDs of two neurons
    number of hops (maybe a slider with options  from 1-6, default 3?)

Graph spec:
  - the graph should follow the type of layout we have for the current graph browser with nodes X number of  hops from a starting node all aligned with each other*, however, layout should be horizontal rather than vertical, with start node on the left and end node on the right.   Styling  should be as for

Example query (Final query would use short_forms) 

```cql
MATCH p=(x:Class)-[:synapsed_to*..4]->(y:Class)
 WHERE x.label = 'abdominal dorsal bipolar neuron dbp' 
 AND y.label = 'A1-7 DO1 motor neuron' RETURN p
```

Example layout from this:

![image](https://user-images.githubusercontent.com/112839/84683010-71279f80-af2e-11ea-98b2-a2da5cd65e77.png)

Colour rendering is by  neo:label (geppeto type).  This does not need to be present in an MVP, but It would be very useful  to be able to have this rendering be user configurable, based on the labels (badges) present. 

Not shown in this example graph:  Edges can have weights.  These should be displayed as both annotations on the edge and as line-thickness.  Examples of these will follow when we load new data (due shortly).

Open questions: 
    How should inputs be chosen?  Maybe  options for setting start and end in TermInfo?
 

The other major use case for circuit browsing is to show all direct connections between a set of neurons.

e.g.

``cql
WITH ['abdominal dorsal bipolar neuron dbp', 'A1-7 DO1 motor neuron', 'larval abdominal dorsal multidendritic neuron dda1' ] as X MATCH p=(x:Class)-[:synapsed_to*..4]->(y:Class) WHERE x.label IN X and y.label in X return p
```

=> 

![image](https://user-images.githubusercontent.com/112839/84684926-4be86080-af31-11ea-9f75-6fe0ac2673c2.png)

I don't think there's an obvious  way to order this.

Could this perhaps be a different mode on the same widget?


\*  Being pinned at two ends, the layout algorithm we're using for the regular graph may not work.  Here's a draft spec I worked up ages ago for layout:

(TBA  @Robbie1977 - do you have this from master student write up?)

**Comment by ddelpiano** [comment]
@dosumis @Robbie1977 below few questions related to the spec above:

**1.** Do you guys want to re-use what currently implemented for the graph regarding how the nodes are displayed or do you prefer something more similar to the screenshots attached above in this card?

**2.** Would it be possible to have a query and 2 short_form we can use to produce some example data to see the output?

**3.** For the colour rendering, 
  **3a.** Would you like to configure this from json based on a pre-set list of labels/type that will drive the association string->color? (e.g. neuron: #484848, and each node of the graph that will have the label neuron will be displayed with this color).
  **3b.** if 3a is not true, would you prefer to have a color picker that lets the user set the color for group of nodes displayed?
  **3c.** which label/properties in the node results will drive the association color->type ?

4. Related to the part of the inputs, my understanding is that we will have 2 neurons to be given in inputs, however I read the below:

"The other major use case for circuit browsing is to show all direct connections between a set of neurons."

Does this means we have to consider cases where we can have more than 2 neurons in inputs?

Thx!

**Comment by dosumis** [comment]
> 1. Do you guys want to re-use what currently implemented for the graph regarding how the nodes are displayed or do you prefer something more similar to the screenshots attached above in this card?

I'm happy to keep the styling the same as the graph.  The important thing is the layout - it should be horizontal, in columns, rather than vertical , in rows (as for graph(context) browser).  Two inputs should be pinned left and right.

> 2. Would it be possible to have a query and 2 short_form we can use to produce some example data to see the output?

FBbt_00002303
FBbt_00002442

> 3. For the colour rendering,
> 3a. Would you like to configure this from json based on a pre-set list of labels/type that will drive the association string->color? (e.g. neuron: #484848, and each node of the graph that will have the label neuron will be displayed with this color).

I think preset is fine

> 3b. if 3a is not true, would you prefer to have a color picker that lets the user set the color for group of nodes displayed?
> 3c. which label/properties in the node results will drive the association color->type ?

List TBA - needs to be configurable/extensible by us - rather than user.

> Related to the part of the inputs, my understanding is that we will have 2 neurons to be given in inputs, however I read the below: "The other major use case for circuit browsing is to show all direct connections between a set of neurons."

> Does this means we have to consider cases where we can have more than 2 neurons in inputs?

I'm not sure we can come up with a unified spec, so maybe this should be two different tools - or 2 modes on one tool.  Important question is whether we can unify the queries and interface:

With 2 inputs, we need to be able to specify number of hops.  With > 2 we probably need to restrict to direct connections to prevent the view from exploding.  With 2 inputs , we need to be able to pint L/R, with >2 inputs, layout in columns no longer makes sense.

**Comment by dosumis** [comment]
Updated query allowing for > 2 neurons

```cql
WITH ['FBbt_00002303',  'FBbt_00002442'] AS neurons 
MATCH p=(x:Class)-[:synapsed_to*..4]->(y:Class)
WHERE x.short_form in neurons and y.short_form in neurons 
RETURN p, len(neurons) and length, neurons
```

if length = 2, the 2 neurons in the list are are pinned to two sides (& layout is columnar)

**Comment by ddelpiano** [comment]
@jrmartin feedback from @Robbie1977 :
- we need to add numbers in the slider, min, max and actual number selected.

**Comment by jrmartin** [comment]
Question on the coloring of the nodes and the edges.
Which label/properties in the node results will drive the association color->type ?

**Comment by Robbie1977** [comment]
@jrmartin the list in the graph node results is 'labels' e.g. 
```"graph": {
            "nodes": [
              {
                "id": "305",
                "labels": [
                  "Class",
                  "VFB",
                  "_Class",
                  "Expression_pattern",
                  "Split",
                  "Entity"
                ],
```

So say we had an (ordered) config file:
```
"Split":"#ff0000", 
"Expression_pattern":"#00ff00",
"Neuron":"#0000ff",
"Class":"#002222"
```
Then it would match on the top results (Split) and so the colour would be Red.

**Comment by jrmartin** [comment]
@Robbie1977 Thanks, another question relating the edges.

"Edges can have weights. These should be displayed as both annotations on the edge and as line-thickness. what data do we have to use to highlight the line thickness? Thx."
