### ISSUE TITLE
Switch color picker

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#780]
https://casesandberg.github.io/react-color/

We need to switch the color picker currently used (that comes from the library mentioned above) with the chrome color picker.

**Comment by ddelpiano** [comment]
test this in the term info, layer and tree component

**Comment by jrmartin** [comment]
Changing the term info picker will take some time, since a PR for geppetto-client will need to be created.

The Term Info uses the geppetto-client's Popup and ButtonBarComponent, and in the latter is where the color picker is initialized https://github.com/openworm/geppetto-client/blob/cc397121e0c67eff08ac1f92d27871911691b5df/js/components/widgets/popup/ButtonBarComponent.js#L271
